### ISSUE TITLE
Inverse functions

### ISSUE THREAD

**Issue by NicoBurno** [ryanve/eol#12]
After the ```eol.split()``` and the machinations with the lines, I need to collect an array of lines back into the string...
The problem is that I do not know what linebreak to use for ```array.join()```...

Maybe we will add support ```eol.getLinebreak()``` or/and ```eol.join(array)```?

**Comment by ryanve** [comment]
Since [0.9.0](https://github.com/ryanve/eol/tree/v0.9.0) you can actually do `[].join(eol.auto)` and it will use the appropriate character. Or you can directly get at it like `String(eol.auto)`. [Via #14](https://github.com/ryanve/eol/pull/14) I just added [documentation for this](https://github.com/ryanve/eol/tree/3f72d6d94262ddc0ff760419b59e30d9b1bdf677#joining). How's that?

**Comment by NicoBurno** [comment]
@ryanve, thanks for the documentation! This is really better than the functions I proposed

**Comment by ryanve** [comment]
For sure—sweet! [That idea](https://github.com/ryanve/eol/pull/11) came from @usergenic
